### ISSUE TITLE
"- Ethernet1: localhost:Ethernet1" pattern should fail provisioning neihgbordb entry

### ISSUE THREAD

**Issue by advornic** [arista-eosplus/ztpserver#24]
```
- name: ok global 1
  definition: test
  interfaces:
    - Ethernet1: localhost:Ethernet1
```

I think this is not possible in practice. We should log an error message an avoid provisioning this node in neighbordb.
