### ISSUE TITLE
Could we use model information from POST /nodes to match patterns in neighbordb?

### ISSUE THREAD

**Issue by phil-dileo** [arista-eosplus/ztpserver#263]
Thinking out loud here...
An issue was raised where provisioning failed on a 7124s because the default pattern in neighbordb "any: any:any" pointed to a definition that specified an install_image action where the EOS version was not supported on the device.  I realize this might complicate things, but would it make sense to do something like:

```
patterns:
  - name: 7124 Hardware Upgrade
    definition: oldHardware.definition
    model: 7124s
    interfaces:
      - any: any:any
  - name: standard default upgrade
    definition: defaultUpgrade.definition
    interfaces:
      - any: any:any
```

In this case, if neighbordb matches multiple patterns it would prioritize one that has a match for model.
