### ISSUE TITLE
GET /nodes/<node_id>/definition takes 6+ seconds to process

### ISSUE THREAD

**Issue by phil-arista** [arista-eosplus/ztpserver#269]
Observed this while doing benchmark testing with funkload.

https://gist.github.com/phil-arista/2ae3b7f63e89ee8f4a79

The testcase runs through a mock provisioning sequence like so:
```
    def test_simple(self):
        # The description should be set in the configuration file
        server_url = self.server_url
        # begin of test ---------------------------------------------
        nb_time = self.conf_getInt('test_simple', 'nb_time')
        for i in range(nb_time):
            rand = randrange(0,2540+1)
            mac = str(100000000000 + rand)
            post_data = '{"neighbors": {"Management1": [{"device": "fake", "port": "000c.295a.4f00"}]}, "version": "4.14", "systemmac": "' + mac + '", "model": "vEOS", "serialnumber": ""}'

            self.get(server_url + '/bootstrap', description='Get bootstrap script')
            self.get(server_url + '/bootstrap/config', description='Get bootstrap config')
            self.post(server_url + "/nodes",
                      params=Data('application/json', post_data),
                      description="POST /nodes:" + post_data)
            self.get(server_url + '/nodes/' + mac, description='Get node definition')
            self.get(server_url + '/actions/add_config', description='Get action')
            self.get(server_url + '/files/templates/ma1.template', description='Get template')
            self.get(server_url + '/actions/copy_file', description='Get action')
            self.get(server_url + '/actions/install_image', description='Get action')
            self.get(server_url + '/files/images/vEOS.swi', description='Get SWI')
        # end of test -----------------------------------------------
```
The ZTPServer has a ```any: any:any``` pattern in neighbordb which points to the following definition:
```
---
actions:
  -
    action: add_config
    attributes:
      url: files/templates/ma1.template
      variables:
        ipaddress: allocate('mgmt_subnet')
    name: "configure ma1"
    onstart: "Starting to configure ma1"
    onsuccess: "SUCCESS: ma1 configure"
    onfailure: "FAIL: IM nick@arista.com for help"
  -
    action: add_config
    attributes:
      url: files/templates/system.template
      variables:
        hostname: allocate('tor_hostnames')
        ztpserver: 172.16.130.10
    name: "configure global system"
    onstart: "Starting to add basic system config"
    onsuccess: "SUCCESS: basic config added"
    onfailure: "FAIL: IM nick@arista.com for help"
  -
    action: add_config
    attributes:
      url: files/templates/login.template
    name: "configure auth"
  -
    action: add_config
    attributes:
      url: files/templates/ztpprep.template
    name: "configure ztpprep alias"
  -
    action: add_config
    attributes:
      url: files/templates/configpush.template
      variables: $variables
    name: "configure config push to server"
  -
    action: add_config
    attributes:
      url: files/templates/mlag.template
      variables:
        vlan: 4094
        ipaddress: 10.0.0.1
        subnet: 30
        po: 10
        trkgrp: mlagpeer
        domain: mlag1
        peer: 10.0.0.2
    name: "configure mlag"
    onstart: "Starting to configure MLAG"
    onsuccess: "SUCCESS: MLAG configured"
    onfailure: "FAIL: IM nick@arista.com for help"
  -
    action: add_config
    attributes:
      url: files/templates/xmpp.template
      variables:
        user: lookup('tor_hostnames')
    name: "configure xmpp"
    onstart: "Starting to configure XMPP"
    onsuccess: "SUCCESS: XMPP configured"
    onfailure: "FAIL: IM nick@arista.com for help"
  -
    action: add_config
    attributes:
      url: files/templates/l3.template
      variables:
        loopback: allocate('ip_loopback')
        ipvlan100: allocate('ip_vlan100')
    name: "configure MLAG, VARP, BGP"
    onstart: "Starting to L3 config"
    onsuccess: "SUCCESS: L3 config added"
    onfailure: "FAIL: IM nick@arista.com for help"
  -
    action: add_config
    attributes:
      url: files/templates/bgpauto.template
    name: "configure bgp interface automation event-handler"
  -
    action: copy_file
    always_execute: true
    attributes:
      dst_url: /mnt/flash/
      mode: 777
      overwrite: if-missing
      src_url: files/automate/bgpautoinf.py
    name: "automate BGP peer interface config"
  -
    action: copy_file
    always_execute: true
    attributes:
      dst_url: /mnt/flash/
      mode: 777
      overwrite: if-missing
      src_url: files/automate/ztpprep
    name: "automate reload"
attributes:
  variables:
    ztpserver: 172.16.130.10
name: tora
```
This incorporates some lookup functions.  I think the problem is that for this testing I created some rather large resource files (so that thousands of nodes could be provisioned).

Each of the resource files have about 2400 entries in them which inflates the files size:
```
-rw-r--r--. 1 root root 52514 Dec  4 17:43 ip_vlan100
-rw-r--r--. 1 root root 47434 Dec  4 17:43 ip_loopback
-rw-r--r--. 1 root root 70013 Dec  4 17:43 tor_hostnames
-rw-r--r--. 1 root root 65868 Dec  4 17:43 mgmt_subnet
```
Perhaps that's where we're getting bogged down?
