### ISSUE TITLE
match_remote_interface does not match when the remote interface is not `any`

### ISSUE THREAD

**Issue by jerearista** [arista-eosplus/ztpserver#359]
When matching an expression like below, the remote interface regex will be ignored and always return True if the local interface is `any` or `none`.
```
    - name: rrSPINE2
      definition: spine2
      interfaces:
        - any: regex('DIST\d'):regex('Ethernet[56]/\d+/1')
```
https://github.com/arista-eosplus/ztpserver/blob/81ea3b95d86350404536314e7b4155413a855f48/ztpserver/topology.py#L842-L848
