### ISSUE TITLE
Preserve 64bit EOS filename in install_image

### ISSUE THREAD

**Issue by siguroot** [arista-eosplus/ztpserver#404]
It would be very useful to me to have the EOS image name preserved when install_image copies firmware to flash.

Currently I have this in my definition file:

```
  -
    action: install_image
    always_execute: true
    attributes:
      url: files/images/EOS64-4.30.6M.swi
      version: 4.30.6M
    name: "Install 4.30.6M"
```

When I check the flash for the resulting filename it is `EOS-4.30.6M.swi`.  I believe this is being caused by:

```
image = "EOS-{}.swi".format(version)
```

Wouldn't it be better just to carry over the filename defined in the definition?

Let me know if you want me to put in a pull request.
